# Generated by Django 5.2.17 on 2026-10-01 12:27

import accounts.managers
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Sign-in name. Also the key used to match a directory account.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(blank=True, help_text='Optional. Kept locally so that an account still works when the directory service is unavailable.', max_length=254)),
                ('full_name', models.CharField(blank=True, help_text='Shown instead of the username where space allows.', max_length=255)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('teacher', 'Teacher')], default='teacher', help_text='Administrators manage classrooms, screens and accounts.', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive accounts cannot sign in. Their history is preserved.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['username'],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ['administrator', 'teacher'])), name='accounts_user_role_is_valid')],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
