# Generated by Django 5.2.17 on 2026-10-03 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageAdvancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('tie', 'Needs resolution')], default='processed', help_text="'tie' means the cut fell between classrooms that are level and an administrator must choose. Stored rather than discarded, so the dashboard can show why the stage is still open.", max_length=16)),
                ('advancing_count', models.PositiveIntegerField(blank=True, help_text='The cut-off in force when this was processed, kept as a record.', null=True)),
                ('tie_detail', models.JSONField(blank=True, default=dict, help_text='When a tie was found: the classrooms involved and the figures they were level on. Shown to the administrator who has to resolve it.')),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Who decided this. Null only if the row predates this field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_advancements', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Who resolved a tie. Null while no tie has needed resolving.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_tie_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stage advancement',
                'verbose_name_plural': 'stage advancements',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="For example 'Primary Science Championship 2026'.", max_length=160)),
                ('description', models.TextField(blank=True, help_text='Optional notes for staff, shown on the tournament page.')),
                ('subject', models.CharField(blank=True, db_index=True, help_text="For example 'Science'. Free text, so a new subject needs no code change.", max_length=80)),
                ('grade', models.CharField(blank=True, db_index=True, help_text="For example 'Grade 5'. Free text, matching Classroom.grade.", max_length=64)),
                ('season', models.CharField(blank=True, db_index=True, help_text="For example '2026' or '2025/2026'. Copied into the historical record.", max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', help_text='Moved by the tournament services, never by a form field.', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='The member of staff who set this tournament up.', on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tournament',
                'verbose_name_plural': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('entered', 'Entered'), ('qualified', 'Qualified'), ('eliminated', 'Eliminated'), ('champion', 'Champion'), ('withdrawn', 'Withdrawn')], db_index=True, default='entered', help_text='Where this classroom stands. Moved by the advancement service.', max_length=16)),
                ('aggregate_score', models.PositiveIntegerField(default=0, help_text="Points earned across the stages this classroom has played. Updated when advancement is processed, and shown as a ranking aid only - a stage result is always read from the competition's frozen result.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='classrooms.classroom')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'tournament participant',
                'verbose_name_plural': 'tournament participants',
                'ordering': ['tournament_id', 'classroom__name'],
            },
        ),
        migrations.CreateModel(
            name='StageAdvancementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text="Position in the stage's standings.")),
                ('score', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('tied', models.BooleanField(default=False, help_text='Whether this classroom was level with another on the cut-off.')),
                ('advanced', models.BooleanField(db_index=True, default=False, help_text='Whether it moved to the next stage.')),
                ('advancement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournaments.stageadvancement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancement_entries', to='tournaments.tournamentparticipant')),
            ],
            options={
                'verbose_name': 'stage advancement entry',
                'verbose_name_plural': 'stage advancement entries',
                'ordering': ['advancement_id', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, help_text='Copied from the tournament when it concluded, so history keeps it.', max_length=32)),
                ('subject', models.CharField(blank=True, max_length=80)),
                ('grade', models.CharField(blank=True, max_length=64)),
                ('winner_name', models.CharField(blank=True, help_text='Name as it stood when the championship concluded.', max_length=160)),
                ('standings', models.JSONField(default=list, help_text='Final ranking rows: rank, classroom, score, stages played. Frozen with the rest of the record.')),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('stages_completed', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(help_text='When the championship concluded.')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, help_text='The winning classroom, if the championship produced one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to='classrooms.classroom')),
            ],
            options={
                'verbose_name': 'tournament record',
                'verbose_name_plural': 'tournament records',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('qualification', 'Qualification'), ('semi_final', 'Semi final'), ('final', 'Final')], help_text='Which round this is. One of each type per tournament.', max_length=32)),
                ('name', models.CharField(blank=True, help_text="Optional label. Left blank, the stage type's name is used.", max_length=160)),
                ('order', models.PositiveIntegerField(help_text='1-based order this stage is played in.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Driven by the attached competitions and by advancement.', max_length=16)),
                ('advancing_count', models.PositiveIntegerField(blank=True, help_text='How many classrooms advance to the next stage. Leave blank to advance every classroom that is still in the championship, which is what a final normally does.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'tournament stage',
                'verbose_name_plural': 'tournament stages',
                'ordering': ['tournament_id', 'order'],
            },
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text='The stage this classroom is currently in, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_participants', to='tournaments.tournamentstage'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='eliminated_at_stage',
            field=models.ForeignKey(blank=True, help_text='The stage this classroom was knocked out at, if it was.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminated_participants', to='tournaments.tournamentstage'),
        ),
        migrations.CreateModel(
            name='StageCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.OneToOneField(help_text='The round this stage is played with. Belongs to at most one stage.', on_delete=django.db.models.deletion.PROTECT, related_name='tournament_stage', to='competitions.competition')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='tournaments.tournamentstage')),
            ],
            options={
                'verbose_name': 'stage competition',
                'verbose_name_plural': 'stage competitions',
                'ordering': ['stage_id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='stageadvancement',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advancement', to='tournaments.tournamentstage'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='tournaments_end_not_before_start'),
        ),
        migrations.AddConstraint(
            model_name='stageadvancemententry',
            constraint=models.UniqueConstraint(fields=('advancement', 'participant'), name='tournaments_one_entry_per_participant_advancement'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.UniqueConstraint(fields=('tournament', 'order'), name='tournaments_one_stage_per_position'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.UniqueConstraint(fields=('tournament', 'stage_type'), name='tournaments_one_stage_per_type'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.CheckConstraint(condition=models.Q(('advancing_count__isnull', True), ('advancing_count__gte', 1), _connector='OR'), name='tournaments_advancing_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(fields=('tournament', 'classroom'), name='tournaments_one_entry_per_classroom'),
        ),
    ]
