# Generated by Django 5.2.17 on 2026-10-01 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique classroom name, for example 'Science Lab 1'.", max_length=120, unique=True)),
                ('grade', models.CharField(blank=True, db_index=True, help_text="For example 'Grade 7' or 'Year 2'. Free text.", max_length=64)),
                ('section', models.CharField(blank=True, max_length=64)),
                ('building', models.CharField(blank=True, max_length=120)),
                ('floor', models.CharField(blank=True, max_length=32)),
                ('room_number', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True, help_text='Inactive classrooms are hidden from selection but keep their history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teachers', models.ManyToManyField(blank=True, help_text='Teachers who may see this classroom on their dashboard.', related_name='classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
            ],
            options={
                'verbose_name': 'classroom',
                'verbose_name_plural': 'classrooms',
                'ordering': ['name'],
            },
        ),
    ]
