# Generated by Django 5.2.17 on 2026-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question as it should appear on a screen.')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True or false')], default='multiple_choice', help_text='Determines how a screen renders the question.', max_length=32)),
                ('options', models.JSONField(blank=True, default=list, help_text='Answer options in display order. Empty for true/false.')),
                ('image', models.ImageField(blank=True, help_text='Optional diagram or photograph shown with the question.', null=True, upload_to='questions/')),
                ('duration_seconds', models.PositiveIntegerField(default=30, help_text='Default time allowed to answer, in seconds. A competition may override this for a particular question.')),
                ('active', models.BooleanField(default=True, help_text='Inactive questions are hidden from selection but keep history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
