# Generated by Django 5.2.17 on 2026-10-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.BooleanField(blank=True, help_text='For a true/false question, whether the statement is true.', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, help_text='For a multiple choice question, the option text that is correct. Must match one of the options exactly.', max_length=255),
        ),
    ]
