# Generated by Django 5.2.17 on 2026-10-02 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_correct_answer_question_correct_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Optional explanation shown after the result is revealed. Never sent to a screen while the question is open.'),
        ),
        migrations.AddField(
            model_name='question',
            name='type_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-type settings for ordering, classification and short answer questions. Unused by multiple choice and true/false.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional diagram or photograph shown with the question.', null=True, upload_to='questions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'gif', 'webp'), message='Upload a JPEG, PNG, GIF or WebP image. Other file types are not accepted for a question.')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('true_false', 'True or false'), ('ordering', 'Ordering'), ('classification', 'Classification'), ('short_answer', 'Short answer')], default='multiple_choice', help_text='Determines how a screen renders the question.', max_length=32),
        ),
    ]
