# Generated by Django 5.2.17 on 2026-10-02 19:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('competitions', '0001_initial'),
        ('questions', '0002_question_correct_answer_question_correct_option'),
        ('screens', '0002_interactivescreen_screens_screen_id_unique_ignoring_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standings', models.JSONField(default=list, help_text='Ranked rows as they stood at the finish: rank, classroom, score, correct answers, answers given.')),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Questions asked in the round.')),
                ('answered_count', models.PositiveIntegerField(default=0, help_text='Answers received across the round.')),
                ('winner_name', models.CharField(blank=True, help_text='Leading classroom, if any. Blank when the round had no answers.', max_length=160)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this snapshot was taken.')),
                ('competition', models.OneToOneField(help_text='The round these standings belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.competition')),
            ],
            options={
                'verbose_name': 'competition result',
                'verbose_name_plural': 'competition results',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_points', models.PositiveIntegerField(default=100, help_text='Points awarded for a correct answer. An incorrect answer scores nothing.', validators=[django.core.validators.MaxValueValidator(1000)])),
                ('speed_bonus_max', models.PositiveIntegerField(default=50, help_text="Most extra points available for answering quickly. Set to 0, or switch the mode to 'No speed bonus', to disable the bonus.", validators=[django.core.validators.MaxValueValidator(500)])),
                ('speed_bonus_mode', models.CharField(choices=[('linear', 'Linear decay'), ('none', 'No speed bonus')], default='linear', help_text='How the bonus is earned as the answer period runs down.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(help_text='The round this rule applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rule', to='competitions.competition')),
            ],
            options={
                'verbose_name': 'scoring rule',
                'verbose_name_plural': 'scoring rules',
                'ordering': ['competition_id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='1-based position of the question within the round, copied for reporting.')),
                ('selected_answer', models.JSONField(help_text='Exactly what the classroom chose, as submitted.')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Server time at which the answer was received.')),
                ('response_time_seconds', models.FloatField(help_text='Seconds from the server starting the question to receiving this answer. Computed on the server from its own clock.')),
                ('duration_seconds', models.PositiveIntegerField(help_text='The time allowed for this question, copied for reporting.')),
                ('is_correct', models.BooleanField(help_text='Whether the selection matched the stored answer key.')),
                ('points', models.PositiveIntegerField(default=0, help_text='Points for correctness alone, before any bonus.')),
                ('speed_bonus', models.PositiveIntegerField(default=0, help_text='Bonus points for answering quickly.')),
                ('correct_answer', models.CharField(blank=True, help_text='The answer key as it stood when this was scored, kept so a report can explain the outcome even if the question is later edited.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(help_text="The classroom that answered. Taken from the screen's own connection.", on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='classrooms.classroom')),
                ('competition', models.ForeignKey(help_text='The round this answer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='competitions.competition')),
                ('question', models.ForeignKey(help_text='The question that was asked.', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questions.question')),
                ('screen', models.ForeignKey(blank=True, help_text='The screen the answer arrived on. Kept for network diagnosis; a screen being retired later must not erase the answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='screens.interactivescreen')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ['competition_id', 'position', 'classroom__name'],
                'indexes': [models.Index(fields=['competition', 'position'], name='scoring_answer_by_question_idx')],
                'constraints': [models.UniqueConstraint(fields=('competition', 'question', 'classroom'), name='scoring_one_answer_per_classroom_question')],
            },
        ),
    ]
