# Generated by Django 5.2.17 on 2026-10-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='The answer key as it stood when this was scored, kept so a report can explain the outcome even if the question is later edited. Sized for the longest key an ordering or classification question can produce; see `questions.models` for the item bounds.', max_length=1000),
        ),
    ]
