# Generated by Django 5.2.17 on 2026-10-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="For example 'Science Lab 1 versus Science Lab 2'.", max_length=160)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('question_active', 'Question active'), ('answering_closed', 'Answering closed'), ('showing_result', 'Showing result'), ('next_question', 'Next question'), ('finished', 'Finished')], db_index=True, default='waiting', help_text='Where the round has reached. Advanced by the server or the teacher.', max_length=32)),
                ('current_question_started_at', models.DateTimeField(blank=True, help_text='Server time at which the current question began. This, not a browser clock, is what the countdown is derived from.', null=True)),
                ('current_question_ends_at', models.DateTimeField(blank=True, help_text='Server time at which answering closes for the current question.', null=True)),
                ('question_number', models.PositiveIntegerField(default=0, help_text='1-based position of the current question within the round.')),
                ('total_questions', models.PositiveIntegerField(default=0, help_text='Number of questions in this round.')),
                ('started_at', models.DateTimeField(blank=True, help_text='Set once, when the teacher starts the round.', null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_question', models.ForeignKey(blank=True, help_text='The question currently on screen, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_in_competitions', to='questions.question')),
                ('teacher', models.ForeignKey(help_text='The member of staff running this round.', on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'competition',
                'verbose_name_plural': 'competitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='classrooms.classroom')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='competitions.competition')),
            ],
            options={
                'verbose_name': 'competition classroom',
                'verbose_name_plural': 'competition classrooms',
                'ordering': ['classroom__name'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'classroom'), name='competitions_one_entry_per_classroom')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='1-based order in which this question is asked.')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text="Overrides the question's own duration for this round. Leave blank to use the question's default.", null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.competition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_entries', to='questions.question')),
            ],
            options={
                'verbose_name': 'competition question',
                'verbose_name_plural': 'competition questions',
                'ordering': ['competition', 'position'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'position'), name='competitions_one_question_per_position'), models.UniqueConstraint(fields=('competition', 'question'), name='competitions_question_appears_once')],
            },
        ),
    ]
