# Generated by Django 5.2.17 on 2026-10-01 12:27

import django.core.validators
import django.db.models.deletion
import screens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(default=screens.models.generate_screen_id, editable=False, help_text='Permanent identity of this screen. Generated once, never changed.', max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(16)])),
                ('name', models.CharField(help_text="Descriptive name, for example 'Front interactive board'.", max_length=120)),
                ('is_primary', models.BooleanField(default=False, help_text='The main screen for its classroom. At most one per classroom.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Last observed address. Monitoring data only - never identity.', null=True)),
                ('browser_user_agent', models.CharField(blank=True, help_text='Last observed browser. Monitoring data only - never identity.', max_length=512)),
                ('last_seen', models.DateTimeField(blank=True, editable=False, help_text='Updated by the heartbeat. Never set by an operator.', null=True)),
                ('active', models.BooleanField(default=True, help_text='Deactivate to retire a screen without losing its history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='The classroom this screen belongs to. A screen can be registered before it is installed; assign it when it is placed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='screens', to='classrooms.classroom')),
            ],
            options={
                'verbose_name': 'interactive screen',
                'verbose_name_plural': 'interactive screens',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['last_seen'], name='screens_last_seen_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('classroom__isnull', False), ('is_primary', True)), fields=('classroom',), name='screens_one_primary_per_classroom')],
            },
        ),
    ]
