# Generated by Django 5.2.17 on 2026-10-01 13:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interactivescreen',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('screen_id'), name='screens_screen_id_unique_ignoring_case'),
        ),
    ]
